name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ghc:
          - 8.10.7

    steps:
      - uses: actions/checkout@v3

      - uses: haskell/actions/setup@v2.0.0
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Set all tracked file modification times to the time of their last commit
        run: |
          for f in $(git ls-tree -r -t --full-name --name-only HEAD src/full) ; do
            touch -t $(git log -1 --pretty=format:%cd --date=format:%Y%m%d%H%M.%S HEAD -- "$f") "$f";
          done

      - name: Freeze Cabal plan
        run: cabal freeze

      - name: Cache Cabal build artifacts
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell-build-env.outputs.cabal-store }}
            dist-newstyle
          key: fresh4-${{ runner.os }}-cabal-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            fresh4-${{ runner.os }}-cabal-${{ matrix.ghc }}

      - name: Build
        run: |
          cabal update
          cabal build
