name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ghc:
          - 8.10.7

    steps:
      - uses: actions/checkout@v3

      - uses: haskell/actions/setup@v2.0.0
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true
          stack-version: 'latest'

      - uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            .stack-work
          # best effort for cache: tie it to Stack resolver and package config
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock', 'package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack
      # - name: Set all tracked file modification times to the time of their last commit
      #   run: |
      #     rev=HEAD
      #     for f in $(git ls-tree -r -t --full-name --name-only "$rev") ; do
      #         touch -d $(git log --pretty=format:%cI -1 "$rev" -- "$f") "$f";
      #     done

      - name: Freeze Cabal plan
        run: cabal freeze

      - name: Cache Cabal build artifacts
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell-build-env.outputs.cabal-store }}
            dist-newstyle
          key: fresh4-${{ runner.os }}-cabal-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            fresh4-${{ runner.os }}-cabal-${{ matrix.ghc }}

      - name: Build with cabal
        run: |
          cabal update
          cabal build

      - name: Build with stack
        run: |
          stack build
